spring:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/pdv
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver
  jackson:
    time-zone: America/Argentina/Buenos_Aires
  jpa:
    generate-dll: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
    show-sql: false


#tenants
tenants:
  datasources:
    pdv:
      jdbcUrl: jdbc:postgresql://localhost:5432/pdv
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 12345
    pdv2:
      jdbcUrl: jdbc:postgresql://localhost:5432/pdv2
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 12345

server:
  port: 8000