spring:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/pdv
    username: postgres
    password: prysoft
    driverClassName: org.postgresql.Driver
  jackson:
    time-zone: America/Argentina/Buenos_Aires
  jpa:
    generate-dll: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
    show-sql: false

#tenants
tenants:
  datasources:
    fragancias:
      jdbcUrl: jdbc:postgresql://localhost:5432/fragancias
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 12345
    servipack:
      jdbcUrl: jdbc:postgresql://localhost:5432/servipack
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 12345
    sprosario:
      jdbcUrl: jdbc:postgresql://localhost:5432/sprosario
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 12345
    lanteriservice:
      jdbcUrl: jdbc:postgresql://localhost:5432/lanteriservice
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 12345
    casanaranja:
      jdbcUrl: jdbc:postgresql://localhost:5432/casanaranja
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 12345
    casasonia:
      jdbcUrl: jdbc:postgresql://localhost:5432/casasonia
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 12345
    pdv:
      jdbcUrl: jdbc:postgresql://localhost:5432/pdv
      driverClassName: org.postgresql.Driver
      username: postgres
      password: prysoft
    fragancias2:
      jdbcUrl: jdbc:postgresql://localhost:5432/fragancias2
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 12345
    tiendanautica:
      jdbcUrl: jdbc:postgresql://localhost:5432/tiendanautica
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 12345
    spoutlet:
      jdbcUrl: jdbc:postgresql://localhost:5432/spoutlet
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 12345
server:
  port: 8000
